/*****************************************************************************/
/****     Copyright (C) 2005                                              ****/
/****     António Manuel Rodrigues Manso                                  ****/
/****     e-mail: manso@ipt.pt                                            ****/
/****     url   : http://orion.ipt.pt/~manso    manso@ipt.pt              ****/
/****     Instituto Politécnico de Tomar                                  ****/
/****     Escola Superior de Tecnologia de Tomar                          ****/
/*****************************************************************************/
/*  This library is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
/*
 * MemoryVariable.java
 *
 * Created on 19 de Outubro de 2005, 10:56
 */

package VisualFluxogram.GUI;

import Portugol.Language.Parse.Symbol;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author  manso
 */
public class MemoryVariable extends javax.swing.JPanel {
    
    /** Creates new form MemoryVariable */
    private Symbol var;
    
    public MemoryVariable(Symbol v) {
        initComponents();
        var = v;
        name.setText( var.getName());
        name.setBackground(color[ var.getLevel()%8]);
        value.setSize(100,20);
        value.setText( var.getValue());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        name = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        value = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1));

        name.setText("jButton1");
        name.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        name.setDefaultCapable(false);
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setMargin(new java.awt.Insets(10, 14, 10, 14));
        name.setMaximumSize(new java.awt.Dimension(120, 20));
        name.setMinimumSize(new java.awt.Dimension(120, 20));
        name.setPreferredSize(new java.awt.Dimension(120, 20));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        add(name);

        jLabel1.setText("  ");
        add(jLabel1);

        value.setFont(new java.awt.Font("Tahoma", 1, 12));
        value.setText("jLabel1");
        value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valueMouseClicked(evt);
            }
        });

        add(value);

    }
    // </editor-fold>//GEN-END:initComponents
    
    private void valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valueMouseClicked
        JOptionPane.showMessageDialog(this, var.toString());
    }//GEN-LAST:event_valueMouseClicked
    
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        JOptionPane.showMessageDialog(this, var.toString());
    }//GEN-LAST:event_nameActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton name;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
    private static int c[] = { 1,2,3};
    
    private static Color color[] = {
                new Color(100,250,100),
                new Color(250,250,50),
                new Color(250,128,50),
                new Color(250,50,50),
                new Color(250,128,128),
                new Color(250,50,128),
                new Color(128,50,250),
                new Color(50,50,250),
    };
    
}
