/* Generated By:JJTree: Do not edit this line. ASTArrayDims.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTArrayDims extends SimpleNode {
  public ASTArrayDims(int id) {
    super(id);
  }

  public ASTArrayDims(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=405aec047dd0158b2fd787cd344086c8 (do not edit this line) */
