/* Generated By:JJTree: Do not edit this line. ASTCallFunction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCallFunction extends SimpleNode {

  Token func_name;

  public ASTCallFunction(int id) {
    super(id);
  }

  public ASTCallFunction(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  void setFuncName( Token func_name )
  {
	this.func_name = func_name;
  }
  
  String getFuncName()
  {
	return func_name.image;
  }
  
  Token getTokenFuncName()
  {
	return func_name;
  }
  
}
/* JavaCC - OriginalChecksum=d5af31d8d6f9feba0191f7ba2906913b (do not edit this line) */
