/* Generated By:JJTree: Do not edit this line. ASTDoWhileStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDoWhileStatement extends SimpleNode {
  public ASTDoWhileStatement(int id) {
    super(id);
  }

  public ASTDoWhileStatement(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0d21b3101134c0e1f382adb16ba74242 (do not edit this line) */
