/* Generated By:JJTree: Do not edit this line. ASTEqNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTEqNode extends SimpleNode {
  public ASTEqNode(int id) {
    super(id);
  }

  public ASTEqNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0dc6657579c9114869ac13caf0720fb0 (do not edit this line) */
