/* Generated By:JJTree: Do not edit this line. ASTFormalParameter.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFormalParameter extends SimpleNode {

  private Token param_type;
  private Token param_name;

  public ASTFormalParameter(int id) {
    super(id);
  }

  public ASTFormalParameter(PortugolParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  public void setParamName( Token param_name )
  {
	this.param_name = param_name;
  }
  
  public String getParamName()
  {
	return param_name.image;
  }
  
  public Token getTokenParamName()
  {
	return param_name;
  }
 
  //-----
 
  public void setParamType( Token param_type )
  {
	this.param_type = param_type;
  }
  
  public String getParamType()
  {
	return param_type.image;
  }
  
  public Token getTokenParamType()
  {
	return param_type;
  }
  
}
/* JavaCC - OriginalChecksum=2919189d968eef3f696967bdb222fb1e (do not edit this line) */
