/* Generated By:JJTree: Do not edit this line. ASTFalseNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFalseNode extends SimpleNode {
  public ASTFalseNode(int id) {
    super(id);
  }

  public ASTFalseNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e4e6f45394704476d3098b2e6d9e348f (do not edit this line) */
