/* Generated By:JJTree: Do not edit this line. ASTGNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTGNode extends SimpleNode {
  public ASTGNode(int id) {
    super(id);
  }

  public ASTGNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=28dba17bc0a724dcbf74295fb04203c3 (do not edit this line) */
