/* Generated By:JJTree: Do not edit this line. ASTModNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTModNode extends SimpleNode {
  public ASTModNode(int id) {
    super(id);
  }

  public ASTModNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cbb2e4b5d57f77b5d21de96e1fdd18db (do not edit this line) */
