/* Generated By:JJTree: Do not edit this line. ASTNullNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTNullNode extends SimpleNode {
  public ASTNullNode(int id) {
    super(id);
  }

  public ASTNullNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cb738eb7b7162de466fc0ab97367955b (do not edit this line) */
