/* Generated By:JJTree: Do not edit this line. ASTNEqNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTNEqNode extends SimpleNode {
  public ASTNEqNode(int id) {
    super(id);
  }

  public ASTNEqNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=69977ff1c4c65bd6d1d9caf2bac5d91a (do not edit this line) */
