/* Generated By:JJTree: Do not edit this line. ASTStatements.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTStatements extends SimpleNode {
  public ASTStatements(int id) {
    super(id);
  }

  public ASTStatements(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f7178dd3e44701a2af2fb4211ea1cb90 (do not edit this line) */
