/* Generated By:JJTree: Do not edit this line. ASTXorNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTXorNode extends SimpleNode {
  public ASTXorNode(int id) {
    super(id);
  }

  public ASTXorNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1440f814aa26e243443c7e16cfda9772 (do not edit this line) */
