/* Generated By:JavaCC: Do not edit this line. PortugolParserVisitor.java Version 4.1 */
public interface PortugolParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws Exception;
  public Object visit(ASTStart node, Object data) throws Exception;
  public Object visit(ASTImportDeclaration node, Object data) throws Exception;
  public Object visit(ASTVariableDeclarationList node, Object data) throws Exception;
  public Object visit(ASTVariableDeclaration node, Object data) throws Exception;
  public Object visit(ASTArrayDims node, Object data) throws Exception;
  public Object visit(ASTArrayInitializer node, Object data) throws Exception;
  public Object visit(ASTFunctionDeclaration node, Object data) throws Exception;
  public Object visit(ASTFormalParametersList node, Object data) throws Exception;
  public Object visit(ASTFormalParameter node, Object data) throws Exception;
  public Object visit(ASTStructDeclaration node, Object data) throws Exception;
  public Object visit(ASTStatements node, Object data) throws Exception;
  public Object visit(ASTReturnStatement node, Object data) throws Exception;
  public Object visit(ASTIfStatement node, Object data) throws Exception;
  public Object visit(ASTSwitchStatement node, Object data) throws Exception;
  public Object visit(ASTSwitchLabel node, Object data) throws Exception;
  public Object visit(ASTWhileDoStatement node, Object data) throws Exception;
  public Object visit(ASTDoWhileStatement node, Object data) throws Exception;
  public Object visit(ASTForStatement node, Object data) throws Exception;
  public Object visit(ASTCallFunction node, Object data) throws Exception;
  public Object visit(ASTAssignmentStatement node, Object data) throws Exception;
  public Object visit(ASTOrNode node, Object data) throws Exception;
  public Object visit(ASTAndNode node, Object data) throws Exception;
  public Object visit(ASTXorNode node, Object data) throws Exception;
  public Object visit(ASTEqNode node, Object data) throws Exception;
  public Object visit(ASTNEqNode node, Object data) throws Exception;
  public Object visit(ASTGNode node, Object data) throws Exception;
  public Object visit(ASTLNode node, Object data) throws Exception;
  public Object visit(ASTGENode node, Object data) throws Exception;
  public Object visit(ASTLENode node, Object data) throws Exception;
  public Object visit(ASTAddNode node, Object data) throws Exception;
  public Object visit(ASTSubNode node, Object data) throws Exception;
  public Object visit(ASTMulNode node, Object data) throws Exception;
  public Object visit(ASTDivNode node, Object data) throws Exception;
  public Object visit(ASTModNode node, Object data) throws Exception;
  public Object visit(ASTNegNode node, Object data) throws Exception;
  public Object visit(ASTNotNode node, Object data) throws Exception;
  public Object visit(ASTVariableName node, Object data) throws Exception;
  public Object visit(ASTIndexSelector node, Object data) throws Exception;
  public Object visit(ASTFieldSelector node, Object data) throws Exception;
  public Object visit(ASTCharNode node, Object data) throws Exception;
  public Object visit(ASTIntNode node, Object data) throws Exception;
  public Object visit(ASTRealNode node, Object data) throws Exception;
  public Object visit(ASTStringNode node, Object data) throws Exception;
  public Object visit(ASTTrueNode node, Object data) throws Exception;
  public Object visit(ASTFalseNode node, Object data) throws Exception;
  public Object visit(ASTNullNode node, Object data) throws Exception;
}
/* JavaCC - OriginalChecksum=212f210f2cf3c3947a2a3e4c76cb0ace (do not edit this line) */
