/* Generated By:JJTree: Do not edit this line. ASTCharNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCharNode extends SimpleNode {
  public ASTCharNode(int id) {
    super(id);
  }

  public ASTCharNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4c4c63fa35676e355df78f2826e7877e (do not edit this line) */
