/* Generated By:JJTree: Do not edit this line. ASTFunctionDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFunctionDeclaration extends SimpleNode {

  private Token return_type = new Token(PortugolParserConstants.VOID, PortugolParserConstants.tokenImage[ PortugolParserConstants.VOID+1 ] );
  private Token func_name;

  public ASTFunctionDeclaration(int id) {
    super(id);
  }

  public ASTFunctionDeclaration(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  public void setReturnType( Token return_type )
  {
	this.return_type = return_type;
  }
  
  public void setFuncName( Token func_name )
  {
	this.func_name = func_name;
  }
  //----------
  public String getReturnType()
  {
	return return_type.image;
  }
  
  public String getFuncName()
  {
	return func_name.image;
  }
  
  //----------
  public Token getTokenReturnType()
  {
	return return_type;
  }
  
  public Token getTokenFuncName()
  {
	return func_name;
  }
}
/* JavaCC - OriginalChecksum=c7bc7501cf09a8b5f04d34efe3ec963b (do not edit this line) */
