/* Generated By:JJTree: Do not edit this line. ASTFieldSelector.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFieldSelector extends SimpleNode {
  public ASTFieldSelector(int id) {
    super(id);
  }

  public ASTFieldSelector(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3652422798e9c3deee554536ca35297e (do not edit this line) */
