/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTImportDeclaration extends SimpleNode {

  //String unit_name;
  private Token unit_name;
  
  public ASTImportDeclaration(int id) {
    super(id);
  }

  public ASTImportDeclaration(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  public void setUnitName( Token unit_name )
  {
	this.unit_name = unit_name;
  }
  
  public String getUnitName()
  {
	return unit_name.image;
  }
  
  public Token getTokenUnitName()
  {
	return unit_name;
  }
  
}
/* JavaCC - OriginalChecksum=1e9b01207d96ae4c3e1b4f426ee90a94 (do not edit this line) */
