/* Generated By:JJTree: Do not edit this line. ASTIndexSelector.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIndexSelector extends SimpleNode {
  public ASTIndexSelector(int id) {
    super(id);
  }

  public ASTIndexSelector(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8374b01c0503ee7a52e762a5c080cea7 (do not edit this line) */
