/* Generated By:JJTree: Do not edit this line. ASTNegNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTNegNode extends SimpleNode {
  public ASTNegNode(int id) {
    super(id);
  }

  public ASTNegNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=893b849707ea29030c1eb4440d9bb960 (do not edit this line) */
