/* Generated By:JJTree: Do not edit this line. ASTRealNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRealNode extends SimpleNode {
  public ASTRealNode(int id) {
    super(id);
  }

  public ASTRealNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=61f989ad82313b41d47ceb531b4f9b75 (do not edit this line) */
