/* Generated By:JJTree: Do not edit this line. ASTStringNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTStringNode extends SimpleNode {
  public ASTStringNode(int id) {
    super(id);
  }

  public ASTStringNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=906068a7ee4e23cc4557b4d22a5520e5 (do not edit this line) */
