/* Generated By:JJTree: Do not edit this line. ASTSubNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTSubNode extends SimpleNode {
  public ASTSubNode(int id) {
    super(id);
  }

  public ASTSubNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4cbdc6eea68dbb4557cd9026125197a4 (do not edit this line) */
