/* Generated By:JJTree: Do not edit this line. ASTSwitchLabel.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTSwitchLabel extends SimpleNode {

  boolean is_default = false;

  public ASTSwitchLabel(int id) {
    super(id);
  }

  public ASTSwitchLabel(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  public boolean isDefault()
  {
	return is_default;
  }
  
}
/* JavaCC - OriginalChecksum=6b38687fe3912c6daad0f4361659cbb2 (do not edit this line) */
