/* Generated By:JJTree: Do not edit this line. ASTStructDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTStructDeclaration extends SimpleNode {

  private Token struct_name;

  public ASTStructDeclaration(int id) {
    super(id);
  }

  public ASTStructDeclaration(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  public void setStructName( Token struct_name )
  {
	this.struct_name = struct_name;
  }
  
  public String getStructName()
  {
	return struct_name.image;
  }
  
  public Token getTokenStructName()
  {
	return struct_name;
  }  
}
/* JavaCC - OriginalChecksum=9e97c09f4e09666767dae6c3252545be (do not edit this line) */
