/* Generated By:JJTree: Do not edit this line. ASTTrueNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTTrueNode extends SimpleNode {
  public ASTTrueNode(int id) {
    super(id);
  }

  public ASTTrueNode(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=814735ac639d84d737c40fd14e94327b (do not edit this line) */
