/* Generated By:JJTree: Do not edit this line. ASTVariableName.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVariableName extends SimpleNode {

  private Token var_name;

  public ASTVariableName(int id) {
    super(id);
  }

  public ASTVariableName(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  public void setVarName( Token var_name )
  {
	this.var_name = var_name;
  }
  
  public String getVarName()
  {
	return var_name.image;
  }
 
  public Token getTokenVarName()
  {
	return var_name;
  }
}
/* JavaCC - OriginalChecksum=1973d497c29ab9e047ca8f13ff8e3279 (do not edit this line) */
