/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVariableDeclaration extends SimpleNode {

  private Token var_name;
	
  public ASTVariableDeclaration(int id) {
    super(id);
  }

  public ASTVariableDeclaration(PortugolParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PortugolParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  public void setVarName( Token var_name )
  {
	this.var_name = var_name;
  }
  
  public String getVarName()
  {
	return var_name.image;
  }
  
  public Token getTokenVarName()
  {
	return var_name;
  }
  
}
/* JavaCC - OriginalChecksum=47bc31a1e63b9d16b2e33a2471be7055 (do not edit this line) */
