/* Generated By:JavaCC: Do not edit this line. PortugolParserTreeConstants.java Version 4.1 */
public interface PortugolParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTVARIABLEDECLARATIONLIST = 3;
  public int JJTVARIABLEDECLARATION = 4;
  public int JJTARRAYDIMS = 5;
  public int JJTARRAYINITIALIZER = 6;
  public int JJTFUNCTIONDECLARATION = 7;
  public int JJTFORMALPARAMETERSLIST = 8;
  public int JJTFORMALPARAMETER = 9;
  public int JJTSTRUCTDECLARATION = 10;
  public int JJTSTATEMENTS = 11;
  public int JJTRETURNSTATEMENT = 12;
  public int JJTIFSTATEMENT = 13;
  public int JJTSWITCHSTATEMENT = 14;
  public int JJTSWITCHLABEL = 15;
  public int JJTWHILEDOSTATEMENT = 16;
  public int JJTDOWHILESTATEMENT = 17;
  public int JJTFORSTATEMENT = 18;
  public int JJTCALLFUNCTION = 19;
  public int JJTASSIGNMENTSTATEMENT = 20;
  public int JJTORNODE = 21;
  public int JJTANDNODE = 22;
  public int JJTXORNODE = 23;
  public int JJTEQNODE = 24;
  public int JJTNEQNODE = 25;
  public int JJTGNODE = 26;
  public int JJTLNODE = 27;
  public int JJTGENODE = 28;
  public int JJTLENODE = 29;
  public int JJTADDNODE = 30;
  public int JJTSUBNODE = 31;
  public int JJTMULNODE = 32;
  public int JJTDIVNODE = 33;
  public int JJTMODNODE = 34;
  public int JJTNEGNODE = 35;
  public int JJTNOTNODE = 36;
  public int JJTVARIABLENAME = 37;
  public int JJTINDEXSELECTOR = 38;
  public int JJTFIELDSELECTOR = 39;
  public int JJTCHARNODE = 40;
  public int JJTINTNODE = 41;
  public int JJTREALNODE = 42;
  public int JJTSTRINGNODE = 43;
  public int JJTTRUENODE = 44;
  public int JJTFALSENODE = 45;
  public int JJTNULLNODE = 46;


  public String[] jjtNodeName = {
    "Start",
    "ImportDeclaration",
    "void",
    "VariableDeclarationList",
    "VariableDeclaration",
    "ArrayDims",
    "ArrayInitializer",
    "FunctionDeclaration",
    "FormalParametersList",
    "FormalParameter",
    "StructDeclaration",
    "Statements",
    "ReturnStatement",
    "IfStatement",
    "SwitchStatement",
    "SwitchLabel",
    "WhileDoStatement",
    "DoWhileStatement",
    "ForStatement",
    "CallFunction",
    "AssignmentStatement",
    "OrNode",
    "AndNode",
    "XorNode",
    "EqNode",
    "NEqNode",
    "GNode",
    "LNode",
    "GENode",
    "LENode",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NegNode",
    "NotNode",
    "VariableName",
    "IndexSelector",
    "FieldSelector",
    "CharNode",
    "IntNode",
    "RealNode",
    "StringNode",
    "TrueNode",
    "FalseNode",
    "NullNode",
  };
}
/* JavaCC - OriginalChecksum=9acca9b44f3a6e6096d861a96459c587 (do not edit this line) */
