/*****************************************************************************/
/****     Copyright (C) 2005                                              ****/
/****     António Manuel Rodrigues Manso                                  ****/
/****     e-mail: manso@ipt.pt                                            ****/
/****     url   : http://orion.ipt.pt/~manso    manso@ipt.pt              ****/
/****     Instituto Politécnico de Tomar                                  ****/
/****     Escola Superior de Tecnologia de Tomar                          ****/
/*****************************************************************************/
/*  This library is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
/*
 * MemoryVariable.java
 *
 * Created on 19 de Outubro de 2005, 10:56
 */

package Editor.GUI;

import Portugol.Language.Parse.Symbol;
import Portugol.Language.Parse.SymbolArray;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  manso
 */
public class MemoryVariable extends javax.swing.JPanel {
    
    /** Creates new form MemoryVariable */
    private Symbol var;
    
    public MemoryVariable(Symbol v) {
        initComponents();
        var = v;
        
        int dimHeight = 25;
        
        name.setText( var.getName());
        name.setBackground(color[ var.getLevel()%8]);
        if( v.isConstant())
            table.setBackground(Color.LIGHT_GRAY);
        DefaultTableModel modelo;
        //------------------------ ARRAYS ---------------------------
        if( v instanceof SymbolArray ){
            SymbolArray a = (SymbolArray) v;
            Vector dims = a.getDimensions();
            //--------------------- uma linha ------------------------
            if( dims.size() != 2){
                modelo =  new DefaultTableModel(1,a.getNumElements());
                for( int i=0; i< a.getNumElements() ; i++)
                    modelo.setValueAt( a.getFlatValue(i),0,i);
            }
            //----------------- duas linhas ---------------------------
            else{
            int maxy = Integer.parseInt(dims.get(0).toString());
            int maxx = Integer.parseInt(dims.get(1).toString());
            modelo =  new DefaultTableModel(maxy,maxx);
            for(int y=0; y< maxy; y++)
                for( int x=0; x< maxx ; x++)
                    modelo.setValueAt( a.getFlatValue(y * maxx + x),y,x);
            }
        }
        //------------------------------------------------- variaveis
        else{            
            modelo =  new DefaultTableModel(1,1);
            modelo.setValueAt(v.getValue(),0,0);
        
    }    
    table.setModel( modelo);
    
    int dimWidth = modelo.getValueAt(0,0).toString().length() * 12 + 30;
     for(int y=0;y< table.getColumnCount();y++)
        table.getColumnModel().getColumn(y).setPreferredWidth( dimWidth );

    table.setRowHeight(dimHeight);
    this.setSize(100,200);
}


/** This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        name = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        table = new javax.swing.JTable();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        name.setText("jButton1");
        name.setDefaultCapable(false);
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setMargin(new java.awt.Insets(10, 14, 10, 14));
        name.setMaximumSize(new java.awt.Dimension(120, 20));
        name.setMinimumSize(new java.awt.Dimension(120, 20));
        name.setPreferredSize(new java.awt.Dimension(120, 20));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        add(name);

        jLabel1.setText("  ");
        add(jLabel1);

        table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table.setFont(new java.awt.Font("Courier New", 1, 18));
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setEnabled(false);
        table.setVerifyInputWhenFocusTarget(false);
        add(table);

    }// </editor-fold>//GEN-END:initComponents
    
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        JOptionPane.showMessageDialog(this, var.toString());
    }//GEN-LAST:event_nameActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton name;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private static int c[] = { 1,2,3};
    
    private static Color color[] = {
        new Color(100,250,100),
        new Color(250,250,50),
        new Color(250,128,50),
        new Color(250,50,50),
        new Color(250,128,128),
        new Color(250,50,128),
        new Color(128,50,250),
        new Color(50,50,250),
    };
    
}
